all: predcorr
predcorr:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o nbody_integrator_predcorr nbody_integrator_predcorr.cpp

superlog:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o nbody_integrator_predcorr_superlog nbody_integrator_predcorr_superlog.cpp

verlet:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o nbody_integrator nbody_integrator.cpp


