all: verlet

verlet:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o nbody_integrator nbody_integrator.cpp

predcorr:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o nbody_integrator_predcorr nbody_integrator_predcorr.cpp

