all: neighbour

neighbour:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o neighbour_search neighbour_search.cpp

initials:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o build_initials build_initials.cpp

