all:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lhdf5 -lz -lboost_program_options -o cdat2h5part cdat2h5part.cpp
	
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lhdf5 -lz -lboost_program_options -o tomascii2h5part tomascii2h5part.cpp
