all: kernelTest kernelProfile

kernelTest:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -I../../src -o kernel_test kernel_test.cpp

kernelProfile:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -I../../src -o kernel_profile kernel_profile.cpp

