all: bartonneckman static
	
static:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o static_version static_version.cpp

bartonneckman:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o barton_neckman barton_neckman.cpp

oldmanagers:
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -lboost_program_options -o old_managers old_managers.cpp

